//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/protocol/Messages.msg.
//

#ifndef __SWARMEVOSE_MESSAGES_M_H
#define __SWARMEVOSE_MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace swarmevose {

class CandidateMsg;
class PartialSigMsg;
class SafetyMsg;
class RevokeProposalMsg;
class RevokeVoteMsg;
class SignedAcfUpdateMsg;
class ClusterTransitionCertMsg;

}  // namespace swarmevose

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace swarmevose {

/**
 * Class generated from <tt>src/protocol/Messages.msg:12</tt> by opp_msgtool.
 * <pre>
 * packet CandidateMsg extends veins::BaseFrame1609_4
 * {
 *     string senderId;           // Vehicle's current pseudonym (anonymous)
 *     string candidatePseudonym; // The new pseudonym being proposed
 *     string zkProofSerialized;  // Pre-computed ZK proof from pool
 *     unsigned int epoch;            // Current epoch number
 *     double locationX;          // Claimed position X (for geographic plausibility)
 *     double locationY;          // Claimed position Y
 *     string h0;                 // Vehicle's certified public key (public)
 *     bool isMalicious = false;  // [Simulation only] flag for malicious node testing
 * }
 * </pre>
 */
class CandidateMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string senderId;
    ::omnetpp::opp_string candidatePseudonym;
    ::omnetpp::opp_string zkProofSerialized;
    unsigned int epoch = 0;
    double locationX = 0;
    double locationY = 0;
    ::omnetpp::opp_string h0;
    bool isMalicious_ = false;

  private:
    void copy(const CandidateMsg& other);

  protected:
    bool operator==(const CandidateMsg&) = delete;

  public:
    CandidateMsg(const char *name=nullptr, short kind=0);
    CandidateMsg(const CandidateMsg& other);
    virtual ~CandidateMsg();
    CandidateMsg& operator=(const CandidateMsg& other);
    virtual CandidateMsg *dup() const override {return new CandidateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderId() const;
    virtual void setSenderId(const char * senderId);

    virtual const char * getCandidatePseudonym() const;
    virtual void setCandidatePseudonym(const char * candidatePseudonym);

    virtual const char * getZkProofSerialized() const;
    virtual void setZkProofSerialized(const char * zkProofSerialized);

    virtual unsigned int getEpoch() const;
    virtual void setEpoch(unsigned int epoch);

    virtual double getLocationX() const;
    virtual void setLocationX(double locationX);

    virtual double getLocationY() const;
    virtual void setLocationY(double locationY);

    virtual const char * getH0() const;
    virtual void setH0(const char * h0);

    virtual bool isMalicious() const;
    virtual void setIsMalicious(bool isMalicious);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CandidateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CandidateMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:26</tt> by opp_msgtool.
 * <pre>
 * // ---- PARTIAL_SIG_MSG ----
 * // Response from a validator vehicle: "I verified your ZK proof"
 * // Contains one partial BLS signature
 * packet PartialSigMsg extends veins::BaseFrame1609_4
 * {
 *     string validatorId;        // Validator's pseudonym
 *     string targetPseudonym;    // Which pseudonym was validated
 *     string sigBytes;           // Partial BLS signature (hex)
 *     unsigned int epoch;            // Epoch of validation
 *     string validatorH0;        // Validator's H_0 (for aggregation verification)
 *     bool accepted;             // Did the validator accept the proof?
 *     string rejectReason;       // If rejected: why (for dashboard)
 * }
 * </pre>
 */
class PartialSigMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string validatorId;
    ::omnetpp::opp_string targetPseudonym;
    ::omnetpp::opp_string sigBytes;
    unsigned int epoch = 0;
    ::omnetpp::opp_string validatorH0;
    bool accepted = false;
    ::omnetpp::opp_string rejectReason;

  private:
    void copy(const PartialSigMsg& other);

  protected:
    bool operator==(const PartialSigMsg&) = delete;

  public:
    PartialSigMsg(const char *name=nullptr, short kind=0);
    PartialSigMsg(const PartialSigMsg& other);
    virtual ~PartialSigMsg();
    PartialSigMsg& operator=(const PartialSigMsg& other);
    virtual PartialSigMsg *dup() const override {return new PartialSigMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getValidatorId() const;
    virtual void setValidatorId(const char * validatorId);

    virtual const char * getTargetPseudonym() const;
    virtual void setTargetPseudonym(const char * targetPseudonym);

    virtual const char * getSigBytes() const;
    virtual void setSigBytes(const char * sigBytes);

    virtual unsigned int getEpoch() const;
    virtual void setEpoch(unsigned int epoch);

    virtual const char * getValidatorH0() const;
    virtual void setValidatorH0(const char * validatorH0);

    virtual bool getAccepted() const;
    virtual void setAccepted(bool accepted);

    virtual const char * getRejectReason() const;
    virtual void setRejectReason(const char * rejectReason);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PartialSigMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PartialSigMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:39</tt> by opp_msgtool.
 * <pre>
 * // ---- SAFETY_MSG ----
 * // The main V2V safety broadcast (braking, hazard, position etc.)
 * // Contains the full Proof of Swarm Acceptance
 * packet SafetyMsg extends veins::BaseFrame1609_4
 * {
 *     string senderId;           // Sender's current pseudonym
 *     double speed;              // Vehicle speed (m/s)
 *     double posX;               // Position X
 *     double posY;               // Position Y
 *     double heading;            // Heading in degrees
 *     string eventType;          // "BEACON", "BRAKE", "HAZARD", "EMERGENCY"
 *     string messageSignature;   // Digital signature over payload
 *     // Proof of Swarm Acceptance fields:
 *     string sigmaSerialized;    // Aggregated BLS Sigma_threshold
 *     unsigned int filterEpochAtSigning; // ACF epoch when proof was issued
 *     string clusterId;          // Which cluster validated this vehicle
 *     bool isMalicious = false;  // [Simulation only]
 * }
 * </pre>
 */
class SafetyMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string senderId;
    double speed = 0;
    double posX = 0;
    double posY = 0;
    double heading = 0;
    ::omnetpp::opp_string eventType;
    ::omnetpp::opp_string messageSignature;
    ::omnetpp::opp_string sigmaSerialized;
    unsigned int filterEpochAtSigning = 0;
    ::omnetpp::opp_string clusterId;
    bool isMalicious_ = false;

  private:
    void copy(const SafetyMsg& other);

  protected:
    bool operator==(const SafetyMsg&) = delete;

  public:
    SafetyMsg(const char *name=nullptr, short kind=0);
    SafetyMsg(const SafetyMsg& other);
    virtual ~SafetyMsg();
    SafetyMsg& operator=(const SafetyMsg& other);
    virtual SafetyMsg *dup() const override {return new SafetyMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderId() const;
    virtual void setSenderId(const char * senderId);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getPosX() const;
    virtual void setPosX(double posX);

    virtual double getPosY() const;
    virtual void setPosY(double posY);

    virtual double getHeading() const;
    virtual void setHeading(double heading);

    virtual const char * getEventType() const;
    virtual void setEventType(const char * eventType);

    virtual const char * getMessageSignature() const;
    virtual void setMessageSignature(const char * messageSignature);

    virtual const char * getSigmaSerialized() const;
    virtual void setSigmaSerialized(const char * sigmaSerialized);

    virtual unsigned int getFilterEpochAtSigning() const;
    virtual void setFilterEpochAtSigning(unsigned int filterEpochAtSigning);

    virtual const char * getClusterId() const;
    virtual void setClusterId(const char * clusterId);

    virtual bool isMalicious() const;
    virtual void setIsMalicious(bool isMalicious);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SafetyMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SafetyMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:57</tt> by opp_msgtool.
 * <pre>
 * // ---- REVOKE_PROPOSAL_MSG ----
 * // Broadcast when malicious behaviour is detected
 * // Triggers swarm voting on whether to revoke a pseudonym
 * packet RevokeProposalMsg extends veins::BaseFrame1609_4
 * {
 *     string proposerId;         // Vehicle proposing the revocation
 *     string suspectPseudonym;   // Pseudonym being proposed for revocation
 *     string suspectH0;          // Suspect's claimed H_0
 *     string evidence;           // Description of observed malicious behaviour
 *     unsigned int epoch;            // Current epoch
 *     double evidenceScore;      // Confidence level 0.0-1.0
 * }
 * </pre>
 */
class RevokeProposalMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string proposerId;
    ::omnetpp::opp_string suspectPseudonym;
    ::omnetpp::opp_string suspectH0;
    ::omnetpp::opp_string evidence;
    unsigned int epoch = 0;
    double evidenceScore = 0;

  private:
    void copy(const RevokeProposalMsg& other);

  protected:
    bool operator==(const RevokeProposalMsg&) = delete;

  public:
    RevokeProposalMsg(const char *name=nullptr, short kind=0);
    RevokeProposalMsg(const RevokeProposalMsg& other);
    virtual ~RevokeProposalMsg();
    RevokeProposalMsg& operator=(const RevokeProposalMsg& other);
    virtual RevokeProposalMsg *dup() const override {return new RevokeProposalMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getProposerId() const;
    virtual void setProposerId(const char * proposerId);

    virtual const char * getSuspectPseudonym() const;
    virtual void setSuspectPseudonym(const char * suspectPseudonym);

    virtual const char * getSuspectH0() const;
    virtual void setSuspectH0(const char * suspectH0);

    virtual const char * getEvidence() const;
    virtual void setEvidence(const char * evidence);

    virtual unsigned int getEpoch() const;
    virtual void setEpoch(unsigned int epoch);

    virtual double getEvidenceScore() const;
    virtual void setEvidenceScore(double evidenceScore);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RevokeProposalMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RevokeProposalMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:68</tt> by opp_msgtool.
 * <pre>
 * // ---- REVOKE_VOTE_MSG ----
 * // Vote from a validator that has independently observed the suspicious behaviour
 * packet RevokeVoteMsg extends veins::BaseFrame1609_4
 * {
 *     string voterId;            // Voter's pseudonym
 *     string suspectPseudonym;   // Who they are voting to revoke
 *     string partialSigBytes;    // Partial BLS sig over revocation proposal
 *     unsigned int epoch;
 *     bool vote;                 // true = revoke, false = reject proposal
 * }
 * </pre>
 */
class RevokeVoteMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string voterId;
    ::omnetpp::opp_string suspectPseudonym;
    ::omnetpp::opp_string partialSigBytes;
    unsigned int epoch = 0;
    bool vote = false;

  private:
    void copy(const RevokeVoteMsg& other);

  protected:
    bool operator==(const RevokeVoteMsg&) = delete;

  public:
    RevokeVoteMsg(const char *name=nullptr, short kind=0);
    RevokeVoteMsg(const RevokeVoteMsg& other);
    virtual ~RevokeVoteMsg();
    RevokeVoteMsg& operator=(const RevokeVoteMsg& other);
    virtual RevokeVoteMsg *dup() const override {return new RevokeVoteMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getVoterId() const;
    virtual void setVoterId(const char * voterId);

    virtual const char * getSuspectPseudonym() const;
    virtual void setSuspectPseudonym(const char * suspectPseudonym);

    virtual const char * getPartialSigBytes() const;
    virtual void setPartialSigBytes(const char * partialSigBytes);

    virtual unsigned int getEpoch() const;
    virtual void setEpoch(unsigned int epoch);

    virtual bool getVote() const;
    virtual void setVote(bool vote);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RevokeVoteMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RevokeVoteMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:79</tt> by opp_msgtool.
 * <pre>
 * // ---- SIGNED_ACF_UPDATE_MSG ----
 * // Broadcast after k revocation votes collected
 * // Contains the fingerprint to insert and the threshold signature proving consensus
 * packet SignedAcfUpdateMsg extends veins::BaseFrame1609_4
 * {
 *     string revokedFingerprint; // SHA256 of revoked pseudonym
 *     string sigmaSerialized;    // Aggregated BLS over the revocation
 *     unsigned int newEpoch;         // New ACF epoch after this update
 *     string clusterId;          // Issuing cluster
 *     string stateHash;          // New filter state hash
 * }
 * </pre>
 */
class SignedAcfUpdateMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string revokedFingerprint;
    ::omnetpp::opp_string sigmaSerialized;
    unsigned int newEpoch = 0;
    ::omnetpp::opp_string clusterId;
    ::omnetpp::opp_string stateHash;

  private:
    void copy(const SignedAcfUpdateMsg& other);

  protected:
    bool operator==(const SignedAcfUpdateMsg&) = delete;

  public:
    SignedAcfUpdateMsg(const char *name=nullptr, short kind=0);
    SignedAcfUpdateMsg(const SignedAcfUpdateMsg& other);
    virtual ~SignedAcfUpdateMsg();
    SignedAcfUpdateMsg& operator=(const SignedAcfUpdateMsg& other);
    virtual SignedAcfUpdateMsg *dup() const override {return new SignedAcfUpdateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRevokedFingerprint() const;
    virtual void setRevokedFingerprint(const char * revokedFingerprint);

    virtual const char * getSigmaSerialized() const;
    virtual void setSigmaSerialized(const char * sigmaSerialized);

    virtual unsigned int getNewEpoch() const;
    virtual void setNewEpoch(unsigned int newEpoch);

    virtual const char * getClusterId() const;
    virtual void setClusterId(const char * clusterId);

    virtual const char * getStateHash() const;
    virtual void setStateHash(const char * stateHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SignedAcfUpdateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SignedAcfUpdateMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/protocol/Messages.msg:90</tt> by opp_msgtool.
 * <pre>
 * // ---- CLUSTER_TRANSITION_CERT_MSG ----
 * // Issued by outgoing cluster to vehicle leaving at high speed
 * // Allows new cluster to accept vehicle in ~2ms without full ZK
 * packet ClusterTransitionCertMsg extends veins::BaseFrame1609_4
 * {
 *     string vehiclePseudonym;   // Vehicle being certified
 *     string vehicleH0;          // Vehicle's H_0
 *     string outgoingClusterId;  // Cluster issuing the cert
 *     string sigmaSerialized;    // Threshold sig from outgoing cluster
 *     unsigned int epoch;
 *     double issuedAtX;          // Location where cert was issued
 *     double issuedAtY;
 * }
 * </pre>
 */
class ClusterTransitionCertMsg : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string vehiclePseudonym;
    ::omnetpp::opp_string vehicleH0;
    ::omnetpp::opp_string outgoingClusterId;
    ::omnetpp::opp_string sigmaSerialized;
    unsigned int epoch = 0;
    double issuedAtX = 0;
    double issuedAtY = 0;

  private:
    void copy(const ClusterTransitionCertMsg& other);

  protected:
    bool operator==(const ClusterTransitionCertMsg&) = delete;

  public:
    ClusterTransitionCertMsg(const char *name=nullptr, short kind=0);
    ClusterTransitionCertMsg(const ClusterTransitionCertMsg& other);
    virtual ~ClusterTransitionCertMsg();
    ClusterTransitionCertMsg& operator=(const ClusterTransitionCertMsg& other);
    virtual ClusterTransitionCertMsg *dup() const override {return new ClusterTransitionCertMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getVehiclePseudonym() const;
    virtual void setVehiclePseudonym(const char * vehiclePseudonym);

    virtual const char * getVehicleH0() const;
    virtual void setVehicleH0(const char * vehicleH0);

    virtual const char * getOutgoingClusterId() const;
    virtual void setOutgoingClusterId(const char * outgoingClusterId);

    virtual const char * getSigmaSerialized() const;
    virtual void setSigmaSerialized(const char * sigmaSerialized);

    virtual unsigned int getEpoch() const;
    virtual void setEpoch(unsigned int epoch);

    virtual double getIssuedAtX() const;
    virtual void setIssuedAtX(double issuedAtX);

    virtual double getIssuedAtY() const;
    virtual void setIssuedAtY(double issuedAtY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterTransitionCertMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterTransitionCertMsg& obj) {obj.parsimUnpack(b);}


}  // namespace swarmevose


namespace omnetpp {

template<> inline swarmevose::CandidateMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::CandidateMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::PartialSigMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::PartialSigMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::SafetyMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::SafetyMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::RevokeProposalMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::RevokeProposalMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::RevokeVoteMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::RevokeVoteMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::SignedAcfUpdateMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::SignedAcfUpdateMsg*>(ptr.get<cObject>()); }
template<> inline swarmevose::ClusterTransitionCertMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<swarmevose::ClusterTransitionCertMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SWARMEVOSE_MESSAGES_M_H

